export enum PermissionsEnum {
    read_templates = 'read:templates',
    create_templates = 'create:templates',
    updates_templates = 'updates:templates',
    delete_templates = 'delete:templates',
    read_campaigns = 'read:campaigns',
    create_campaigns = 'create:campaigns',
    update_campaigns = 'update:campaigns',
    delete_campaigns = 'delete:campaigns',
    read_eMailProviders = 'read:eMailProviders',
    create_eMailProviders = 'create:eMailProviders',
    update_eMailProviders = 'update:eMailProviders',
    delete_eMailProviders = 'delete:eMailProviders',
    create_users = 'create:users',
    read_users = 'read:users',
    update_users = 'update:users',
    delete_users = 'delete:users',
    update_manager_role = 'update:manager-role',
    update_owner_role = 'update:owner-role',
    execute_campaigns = 'execute:campaigns',
    approve_templates = 'approve:templates',
    schedule_campaign = 'schedule:campaign',
}
